language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
services:
  - mongodb
  - postgresql
before_script:
  - coffee -c -o build app.coffee
  - coffee -c -o build/src app.coffee
  - cp settings.json build/settings.json
  - psql -c 'create database scrapper;' -U postgres